---

- name: Install MySQL client
  apt:
    name: mysql-client
    state: present

- name: Ensure Drupal default directory exists
  file:
    path: /var/www/html/sites/default
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'


- name: Configure Drupal settings.php with RDS DB connection
  template:
    src: drupal.settings.php.j2
    dest: /var/www/html/sites/default/settings.php
    owner: www-data
    group: www-data
    mode: '0644'
  notify: Restart Apache



- name: Test RDS database connection
  command: >
    mysql -h {{ rds_endpoint }} -u {{ drupal_db_user }} -p{{ drupal_db_pass }} -e "SHOW DATABASES;"
  register: db_test
  changed_when: false
  ignore_errors: true
  

