apiVersion: v1
kind: Service
metadata:
  name: drupal-service
  namespace: drupal-staging
spec:
  type: LoadBalancer
  selector:
    app: drupal
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
