- name: Install Apache
  apt:
    name: apache2
    state: present

- name: Enable mod_rewrite
  apache2_module:
    name: rewrite
    state: present

- name: Set Apache to start on boot
  systemd:
    name: apache2
    enabled: yes

