apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysql.fullname" . }}-secret
  labels:
    app: {{ include "mysql.name" . }}
type: Opaque
data:
  root-password: {{ .Values.mysqlSecrets.rootPassword | b64enc | quote }}
  user: {{ .Values.mysqlSecrets.user | b64enc | quote }}
  password: {{ .Values.mysqlSecrets.password | b64enc | quote }}
  database: {{ .Values.mysqlSecrets.database | b64enc | quote }}
