apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: monitoring
spec:
  serviceAccountName: prometheus
  serviceMonitorNamespaceSelector: {}  # Watch all namespaces
  serviceMonitorSelector: {}          # Select all ServiceMonitors
  resources:
    requests:
      memory: 4Gi
      cpu: 1
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: gp2
        resources:
          requests:
            storage: 20Gi