---
drupal_root: /var/www/html/
drupal_version: "10.2.2"
drupal_download_url: "https://ftp.drupal.org/files/projects/drupal-{{ drupal_version }}.tar.gz"
php_packages:
  - php8.1
  - php8.1-cli
  - php8.1-common
  - php8.1-mysql
  - php8.1-xml
  - php8.1-gd
  - php8.1-curl
  - php8.1-mbstring
  - php8.1-zip
  - php8.1-json
