# group_vars/all.yml

php_version: "8.3"
php_packages:
  - php{{ php_version }}
  - php{{ php_version }}-cli
  - php{{ php_version }}-common
  - php{{ php_version }}-mysql
  - php{{ php_version }}-xml
  - php{{ php_version }}-gd
  - php{{ php_version }}-mbstring
  - libapache2-mod-php{{ php_version }}
  - php{{ php_version }}-curl
  - php{{ php_version }}-zip
state: present
update_cache: yes  
  
php_version: "8.3"  # or auto-generate if needed
php_packages:
  - php
  - php-cli
  - php-common
  - php-mysql
  - php-xml
  - php-gd
  - php-mbstring
  - libapache2-mod-php
  - php-curl
  - php-zip
state: present
update_cache: yes
#load_balancer_dns: drupal-app-alb-1234587071.us-east-1.elb.amazonaws.com

drupal_root: "/var/www/html"
rds_endpoint: drupal-app-db.c3eewgrpysg2.us-east-1.rds.amazonaws.com -P 3306
drupal_db_host: "{{ rds_endpoint }}"
drupal_db_name: "drupaldb"
drupal_db_user: "drupal"
drupal_db_pass: "MyStr0ngPassw0rd-123"
drupal_db_host: "{{ rds_endpoint }}"


# Set timezone
timezone: Africa/Lagos

# Set the deploy user
create_user: ubuntu
ansible_user: ubuntu
ansible_ssh_private_key_file: /home/ubuntu/drupalkey.pem


# Define common packages to install
common_packages:
  - curl
  - unzip
  - git
  - htop
  - ufw
  - fail2ban
  - wget
