# group_vars/all.yml

# Set timezone
timezone: Africa/Lagos

# Set the deploy user
create_user: ubuntu
ansible_user: ubuntu
ansible_ssh_private_key_file: /home/ubuntu/drupalkey.pem


# Define common packages to install
common_packages:
  - curl
  - unzip
  - git
  - htop
  - ufw
  - fail2ban
  - wget
