# group_vars/all.yml
php_version: "8.2"  # or auto-generate if needed
php_packages:
  - php
  - php-cli
  - php-common
  - php-mysql
  - php-xml
  - php-gd
  - php-mbstring
  - libapache2-mod-php
drupal_root: "/var/www/html"

drupal_db_name: "drupal"
drupal_db_user: "drupaluser"
drupal_db_pass: "{{ drupal_db_pass }}"
drupal_db_host: "{{ rds_endpoint }}"


# Set timezone
timezone: Africa/Lagos

# Set the deploy user
create_user: ubuntu
ansible_user: ubuntu
ansible_ssh_private_key_file: /home/ubuntu/drupalkey.pem


# Define common packages to install
common_packages:
  - curl
  - unzip
  - git
  - htop
  - ufw
  - fail2ban
  - wget
