# group_vars/all.yml

php_version: "8.1"
web_root: "/var/www/html/"
drupal_project_dir: "{{ web_root }}drupal"
drupal_site_name: demo_umami



#drupal_root: "/var/www/html"
rds_endpoint: drupal-app-db.c3eewgrpysg2.us-east-1.rds.amazonaws.com -P 3306
drupal_db_host: "{{ rds_endpoint }}"
drupal_db_name: "drupaldb"
drupal_db_user: "drupal"
drupal_db_pass: "MyStr0ngPassw0rd-123"


# Set timezone
timezone: Africa/Lagos

# Set the deploy user
create_user: ubuntu
ansible_user: ubuntu
ansible_ssh_private_key_file: /home/ubuntu/drupalkey.pem


# Define common packages to install
common_packages:
  - curl
  - unzip
  - git
  - htop
  - ufw
  - fail2ban
  - wget
