rds_endpoint: drupal-app-db.c3eewgrpysg2.us-east-1.rds.amazonaws.com:3306
drupal_db_name: "drupaldb"
drupal_db_user: "drupal"
drupal_db_pass: "MyStr0ngPassw0rd-123"
drupal_db_host: "{{ rds_endpoint }}"  # passed from Terraform to Ansible inventory
