drupal_site_name: "MyDrupalSite"
drupal_admin_user: "admin"
drupal_admin_pass: "strongpassword"
drupal_db_name: "drupal"
drupal_db_user: "drupaluser"
drupal_db_pass: "{{ vault_drupal_db_pass }}"
drupal_db_host: "{{ rds_endpoint }}"  # passed from Terraform to Ansible inventory
timezone: "UTC"
