version: '3.8'

services:
  drupal:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./modules:/var/www/html/modules
      - ./themes:/var/www/html/themes
      - ./sites:/var/www/html/sites
    environment:
      - DRUPAL_DATABASE_HOST=db
      - DRUPAL_DATABASE_NAME=drupal
      - DRUPAL_DATABASE_USER=drupal
      - DRUPAL_DATABASE_PASSWORD=drupal
    depends_on:
      - db
    networks:
      - drupal-network

  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=drupal
      - MYSQL_USER=drupal
      - MYSQL_PASSWORD=drupal
      - MYSQL_ROOT_PASSWORD=rootpassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - drupal-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_USER=drupal
      - PMA_PASSWORD=drupal
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - drupal-network

volumes:
  db_data:

networks:
  drupal-network:
    driver: bridge
