apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal
  namespace: drupal
spec:
  replicas: 2
  selector:
    matchLabels:
      app: drupal
  template:
    metadata:
      labels:
        app: drupal
    spec:
      containers:
      - name: drupal
        image: your-dockerhub-username/drupal:latest
        ports:
        - containerPort: 80
        env:
        - name: DRUPAL_DATABASE_HOST
          value: "drupal-mysql"
        - name: DRUPAL_DATABASE_NAME
          value: "drupal"
        - name: DRUPAL_DATABASE_USER
          value: "drupal"
        - name: DRUPAL_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: drupal-db-secret
              key: password
        volumeMounts:
        - name: drupal-data
          mountPath: /var/www/html/sites
      volumes:
      - name: drupal-data
        persistentVolumeClaim:
          claimName: drupal-pvc
