apiVersion: v1
kind: Secret
metadata:
  name: drupal-db-secret
  namespace: drupal
type: Opaque
data:
  password: ZHJ1cGFs # base64 encoded "drupal"
  root-password: cm9vdHBhc3N3b3Jk # base64 encoded "rootpassword"
