apiVersion: v1
kind: Service
metadata:
  name: drupal-service
  namespace: drupal
  labels:                   # Add these
    app: drupal             # Needed for ServiceMonitor
spec:
  selector:
    app: drupal
  ports:
    - name: http            # Named port
      protocol: TCP
      port: 80
      targetPort: 80
    - name: php-fpm-metrics # Must match ServiceMonitor
      protocol: TCP
      port: 9253
      targetPort: 9253
  type: LoadBalancer