apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: drupal
type: Opaque
data:
  mysql-root-password: bXlzcWxyb290cGFzcw==    # base64 for 'mysqlrootpass'
  mysql-database: ZHJ1cGFs                    # base64 for 'drupal'
  mysql-user: ZHJ1cGFsdXNlcg==                # base64 for 'drupaluser'
  mysql-password: ZHJ1cGFscGFzcw==            # base64 for 'drupalpass'
