apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  root-password: cm9vdHBhc3N3b3Jk  # base64 encoded "rootpassword"
  db-password:   ZHJ1cGFscGFzc3dvcmQ=  # base64 encoded "drupalpassword"
