---
- name: Ensure Drupal files directory exists
  ansible.builtin.file:
    path: /var/www/html/sites/default/files
    state: directory
    owner: www-data
    group: www-data
    mode: '0775'
    recurse: yes

- name: Rsync Drupal files from app-server-1 to app-server-2 (run from Bastion)
  delegate_to: localhost  # or delegate_to: bastion
  become: false
  command: >
    rsync --delay-updates -F --compress --archive
    --rsh='ssh -i ~/drupalkey.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
    --rsync-path='sudo -u root rsync'
    --exclude=*.tmp
    ubuntu@10.1.3.15:/var/www/html/sites/default/files/
    ubuntu@10.1.4.139:/var/www/html/sites/default/files/
    

- name: Sync Drupal files directory from master node (optional)
  ansible.posix.synchronize:
    src: /var/www/html/sites/default/files/
    dest: /var/www/html/sites/default/files/
    recursive: yes
    delete: no
    rsync_opts:
      - "--exclude=*.tmp"
  delegate_to: "{{ groups['web'][0] }}"


