---
- name: Ensure Drupal files directory exists
  ansible.builtin.file:
    path: /var/www/html/sites/default/files
    state: directory
    owner: www-data
    group: www-data
    mode: '0775'
    recurse: yes

- name: Sync Drupal files directory from master node (optional)
  ansible.posix.synchronize:
    src: /var/www/html/sites/default/files/
    dest: /var/www/html/sites/default/files/
    recursive: yes
    delete: no
    rsync_opts:
      - "--exclude=*.tmp"
  delegate_to: "{{ groups['web'][0] }}"


