---
- name: Ensure Drupal files directory exists
  ansible.builtin.file:
    path: /var/www/html/sites/default/files
    state: directory
    owner: www-data
    group: www-data
    mode: '0775'
    recurse: yes

- name: Step 1 - Copy files from app-server-1 to bastion (local)
  delegate_to: localhost
  ansible.builtin.shell: |
    rsync --delay-updates -F --compress --archive \
    --rsh="ssh -i ~/drupalkey.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" \
    --rsync-path="sudo -u root rsync" \
    --exclude=*.tmp \
    ubuntu@10.1.3.15:/var/www/html/sites/default/files/ /tmp/drupal_files/

- name: Step 2 - Copy files from bastion (local) to app-server-2
  delegate_to: localhost
  ansible.builtin.shell: |
    rsync --delay-updates -F --compress --archive \
    --rsh="ssh -i ~/drupalkey.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" \
    --rsync-path="sudo -u root rsync" \
    --exclude=*.tmp \
    /tmp/drupal_files/ ubuntu@10.1.4.139:/var/www/html/sites/default/files/

    

- name: Sync Drupal files directory from master node (optional)
  ansible.posix.synchronize:
    src: /var/www/html/sites/default/files/
    dest: /var/www/html/sites/default/files/
    recursive: yes
    delete: no
    rsync_opts:
      - "--exclude=*.tmp"
  delegate_to: "{{ groups['web'][0] }}"


