---
- name: Install rsync
  apt:
    name: rsync
    state: present
  become: true

- name: Ensure destination directory exists
  file:
    path: "{{ drupal_project_dir }}/web/sites/default/files"
    state: directory
    mode: '0755'
  become: true

- name: Sync files from primary node to secondary nodes
  become: true
  delegate_to: "{{ inventory_hostname }}"
  run_once: false
  when: inventory_hostname != 'app-server-1'
  command: >
    rsync -az --delete -e "ssh -o StrictHostKeyChecking=no"
    ubuntu@10.1.3.64:{{ drupal_project_dir }}/web/sites/default/files/
    {{ drupal_project_dir }}/web/sites/default/files/

#- name: Step 1 - Copy files from app-server-1 to bastion (local)
 # delegate_to: localhost
  #ansible.builtin.shell: |
   # rsync --delay-updates -F --compress --archive \
    #--rsh="ssh -i ~/drupalkey.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" \
   # --rsync-path="sudo -u root rsync" \
   # --exclude=*.tmp \
   # ubuntu@10.1.3.15:/var/www/html/sites/default/files/ /tmp/drupal_files/

#- name: Step 2 - Copy files from bastion (local) to app-server-2
 # delegate_to: localhost
  #ansible.builtin.shell: |
   # rsync --delay-updates -F --compress --archive \
    #--rsh="ssh -i ~/drupalkey.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" \
    #--rsync-path="sudo -u root rsync" \
   # --exclude=*.tmp \
   # /tmp/drupal_files/ ubuntu@10.1.4.139:/var/www/html/sites/default/files/

    



