---
- name: Ensure Apache modules for reverse proxy support are enabled (Debian-based)
  ansible.builtin.command: a2enmod headers
  notify: Restart Apache
  when: ansible_os_family == "Debian"

- name: Verify Drupal web directory exists
  ansible.builtin.stat:
    path: "{{ web_root }}"
  register: web_dir
  vars:
    web_root: "{{ drupal_project_dir | default('/var/www/html') }}/drupal"

- name: Create Drupal web directory if missing
  ansible.builtin.file:
    path: "{{ web_root }}"
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'
  when: not web_dir.stat.exists

- name: Ensure .htaccess exists
  block:
    - name: Check for existing .htaccess
      ansible.builtin.stat:
        path: "{{ web_root }}/.htaccess"
      register: htaccess_file

    - name: Create basic .htaccess
      ansible.builtin.copy:
        content: |
          <IfModule mod_rewrite.c>
            RewriteEngine on
            RewriteBase /
            RewriteCond %{REQUEST_FILENAME} !-f
            RewriteCond %{REQUEST_FILENAME} !-d
            RewriteRule ^(.*)$ index.php?q=$1 [L,QSA]
          </IfModule>
        dest: "{{ drupal_web_root }}/.htaccess"
        owner: www-data
        group: www-data
        mode: '0644'
      when: not htaccess_file.stat.exists

- name: Add reverse proxy settings
  ansible.builtin.blockinfile:
    path: "{{ web_root }}/.htaccess"
    marker: "# {mark} ANSIBLE MANAGED LB CONFIG"
    block: |
      SetEnvIf X-Forwarded-Proto https HTTPS=on
      RewriteCond %{HTTP:X-Forwarded-Proto} !https
      RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
    insertafter: 'RewriteEngine on'

- name: Add trusted host patterns to Drupal settings
  ansible.builtin.blockinfile:
    path: "{{ web_root }}/sites/default/settings.php"
    marker: "# {mark} ANSIBLE MANAGED ALB CONFIG"
    block: |
      $settings['trusted_host_patterns'] = [
        '^{{ alb_dns_name }}$',
      ];
      $settings['reverse_proxy'] = TRUE;
      $settings['reverse_proxy_addresses'] = [$_SERVER['REMOTE_ADDR']];
  when: alb_dns_name is defined
