---
- name: Install Composer globally
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-setup.php

- name: Run Composer installer
  command: php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer
  args:
    creates: /usr/local/bin/composer

- name: Install Drush (Drupal CLI)
  command: composer global require drush/drush
  environment:
    COMPOSER_HOME: /root/.composer
  args:
    creates: /root/.composer/vendor/bin/drush

- name: Symlink Drush binary to make it globally available
  file:
    src: /root/.composer/vendor/bin/drush
    dest: /usr/local/bin/drush
    state: link
    force: yes

- name: Change ownership of Drupal directory
  file:
    path: /var/www/html
    owner: www-data
    group: www-data
    recurse: yes

- name: Install Drupal site using Drush
  command: >
    drush site-install standard
    --db-url=mysql://{{ db_user }}:{{ db_password }}@{{ db_host }}/{{ db_name }}
    --account-name=admin
    --account-pass=admin123
    --site-name="Drupal HA Site"
    --yes
  args:
    chdir: /var/www/html
  environment:
    PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/.composer/vendor/bin"
  register: drush_output
  ignore_errors: yes

- name: Debug output of Drush install
  debug:
    var: drush_output.stdout_lines
