---
- name: Ensure apt cache is updated
  apt:
    update_cache: yes

- name: Install Apache
  apt:
    name: apache2
    state: present

- name: Enable Apache modules
  apache2_module:
    name: "{{ item }}"
    state: present
  loop:
    - rewrite
    - headers
  notify: Restart Apache

- name: Add PHP 8.1 PPA
  apt_repository:
    repo: ppa:ondrej/php
    state: present
    update_cache: yes

- name: Pin PHP version
  copy:
    dest: /etc/apt/preferences.d/php
    content: |
      Package: php*
      Pin: version {{ php_version }}*
      Pin-Priority: 1001
  notify: Update apt cache

- name: Install PHP 8.1 and extensions
  apt:
    name: "{{ php_packages }}"
    state: present

- name: Set default PHP version
  alternatives:
    name: php
    path: "/usr/bin/php{{ php_version }}"
  ignore_errors: yes

- name: Copy custom php.ini
  copy:
    src: php.ini
    dest: "/etc/php/{{ php_version }}/apache2/php.ini"
    owner: root
    group: root
    mode: '0644'
  notify: Restart Apache

- name: Create Drupal root directory
  file:
    path: "{{ drupal_root }}"
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'
    recurse: yes

- name: Set Drupal version
  set_fact:
    drupal_version: "10.2.3"  # <-- set your desired version here

- name: Download specific Drupal version
  get_url:
    url: "https://ftp.drupal.org/files/projects/drupal-{{ drupal_version }}.tar.gz"
    dest: /tmp/drupal.tar.gz

- name: Extract Drupal into web root
  unarchive:
    src: /tmp/drupal.tar.gz
    dest: "{{ drupal_root }}"
    remote_src: yes
    extra_opts: [--strip-components=1]
    creates: "{{ drupal_root }}/index.php"

- name: Ensure sites/default directory exists
  file:
    path: "{{ drupal_root }}/sites/default"
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: Deploy drupal settings.php 
  template:
    src: settings.php
    dest: "{{ drupal_root }}/sites/default/settings.php"
    owner: www-data
    group: www-data
    mode: '0644'

- name: Copy Apache Drupal VirtualHost config
  template:
    src: drupal.conf.j2
    dest: /etc/apache2/sites-available/drupal.conf
  notify: Restart Apache

- name: Enable Drupal site
  command: a2ensite drupal.conf
  args:
    creates: /etc/apache2/sites-enabled/drupal.conf
  notify: Restart Apache

- name: Disable default Apache site
  command: a2dissite 000-default.conf
  args:
    removes: /etc/apache2/sites-enabled/000-default.conf
  notify: Restart Apache

- name: Set permissions for Drupal files
  file:
    path: "{{ drupal_root }}"
    state: directory
    recurse: yes
    owner: www-data
    group: www-data
