---
- name: Apply common base configuration to all servers
  hosts: all
  become: true
  roles:
    - common
     
- name: Set up web environment
  hosts: app
  become: true
  roles:
    - php
    - apache
    - composer
    - web
    - dbclient
    - drupal
    - filesync
    - harden
