---
- name: Apply common base configuration to all servers
  hosts: all
  become: yes
  roles:
    - common
     
- name: Set up web environment
  hosts: app
  become: yes
  roles:
    - php
    - apache
    - composer
    - drupal
    - filesync
    - harden
