---
- name: Apply common base configuration to all servers
  hosts: all
  become: true
  roles:
    - common

- name: Deploy Drupal Infrastructure
  hosts: web
  become: true
  vars:
    php_version: "8.1"
    php_packages:
      - php{{ php_version }}
      - libapache2-mod-php{{ php_version }}
      - php{{ php_version }}-mysql
      - php{{ php_version }}-xml
      - php{{ php_version }}-gd
      - php{{ php_version }}-curl
      - php{{ php_version }}-mbstring
      - php{{ php_version }}-zip
      - php{{ php_version }}-dom
    drupal_root: /var/www/html/drupal
  roles:
    - web
     

- name: Provision Drupal Web Servers
  hosts: web
  become: true
  roles:
    - web
    - dbclient
    - drupal
    - filesync
    - harden
