---
- name: Apply common base configuration to all servers
  hosts: all
  become: true
  roles:
    - common

- name: Provision Drupal Web Servers
  hosts: web
  become: true
  roles:
    - web
    - dbclient
    - drupal
    - filesync
    - harden
