- name: Copy default.settings.php to settings.php
  copy:
    src: "{{ drupal_project_dir }}/web/sites/default/default.settings.php"
    dest: "{{ drupal_project_dir }}/web/sites/default/settings.php"
    remote_src: yes
    owner: www-data
    group: www-data
    mode: 0644

- name: Configure database settings
  lineinfile:
    path: "{{ drupal_project_dir }}/web/sites/default/settings.php"
    regexp: "^\\$databases\\['default'\\]\\['default'\\] = array"
    line: |
      $databases['default']['default'] = array (
        'database' => '{{ drupal_db_name }}',
        'username' => '{{ drupal_db_user }}',
        'password' => '{{ drupal_db_password }}',
        'host' => '{{ drupal_db_host }}',
        'driver' => 'mysql',
        'port' => '3306',
        'prefix' => '',
      );
    state: present
    insertafter: EOF
