- name: Ensure ~/.bashrc exists
  file:
    path: "{{ ansible_env.HOME }}/.bashrc"
    state: touch

- name: Add Composer global bin to PATH
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: 'export PATH="$HOME/.config/composer/vendor/bin:$PATH"'
    insertafter: EOF
    state: present

- name: Install Drush globally using Composer
  shell: composer global require drush/drush --no-interaction
  environment:
    COMPOSER_HOME: "{{ ansible_env.HOME }}/.config/composer"
  args:
    creates: "{{ ansible_env.HOME }}/.config/composer/vendor/bin/drush"

- name: Symlink Drush to /usr/local/bin for global access
  become: true
  file:
    src: "{{ ansible_env.HOME }}/.config/composer/vendor/bin/drush"
    dest: /usr/local/bin/drush
    state: link
    force: yes
