- name: Ensure required packages are installed
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:  
      - curl
      - unzip
      - php
      - php-mysql
      - php-gd
      - php-xml
      - php-mbstring
      - php-curl
      - php-zip
      - apache2
    
  

- name: Download latest Drupal release
  get_url:
    url: https://www.drupal.org/download-latest/tar.gz
    dest: /tmp/drupal.tar.gz
    mode: '0644'

- name: Remove previous extracted Drupal folder (if any)
  file:
    path: "/tmp/drupal-10.2.5"
    state: absent

- name: Extract Drupal archive to /tmp
  unarchive:
    src: /tmp/drupal.tar.gz
    dest: /tmp/
    remote_src: yes

- name: Clean existing web root
  file:
    path: /var/www/html
    state: absent

- name: Recreate web root directory
  file:
    path: /var/www/html
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: Copy Drupal files to web root
  shell: cp -r /tmp/drupal-*/. /var/www/html/
  args:
    executable: /bin/bash

- name: Set ownership and permissions
  file:
    path: /var/www/html
    state: directory
    recurse: yes
    owner: www-data
    group: www-data

- name: Configure Apache virtual host for Drupal
  template:
    src: drupal.conf.j2
    dest: /etc/apache2/sites-available/drupal.conf
  notify:
    - Reload Apache

- name: Enable Drupal site and disable default
  shell: |
    a2dissite 000-default.conf || true
    a2ensite drupal.conf
  notify:
    - Reload Apache


- name: Restart Apache
  service:
    name: apache2
    state: restarted
