---
- name: Create web root directory
  file:
    path: "{{ web_root }}"
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: Remove existing Drupal directory (if re-provisioning)
  file:
    path: "{{ drupal_project_dir }}"
    state: absent    
    

- name: Create Drupal project directory
  file:
    path: "{{ drupal_project_dir }}"
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: Download Drupal using Composer
  shell: >
    COMPOSER_ALLOW_SUPERUSER=1
    composer create-project --no-interaction --prefer-dist drupal/recommended-project "{{ drupal_project_dir }}"
  args:
    creates: "{{ drupal_project_dir }}"

- name: Quick start Drupal site (Umami demo)
  shell: php -d memory_limit=256M web/core/scripts/drupal quick-start demo_umami
  args:
    chdir: "{{ drupal_project_dir }}"
    creates: "{{ drupal_project_dir }}/web/sites/default/settings.php"

- import_tasks: db_config.yml
