---
- name: Ensure web root directory exists
  file:
    path: "{{ web_root }}"
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: Remove existing Drupal directory (if re-provisioning)
  file:
    path: "{{ drupal_project_dir }}"
    state: absent
  when: force_redeploy | default(false)

- name: Create Drupal project directory
  file:
    path: "{{ drupal_project_dir }}"
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: Download Drupal using Composer
  command: composer create-project drupal/recommended-project "{{ drupal_project_dir }}"
  args:
    chdir: "{{ web_root }}"
    creates: "{{ drupal_project_dir }}/composer.json"
  environment:
    COMPOSER_ALLOW_SUPERUSER: "1"

- name: Quick start Drupal site (Umami demo)
  shell: >
    php -d memory_limit=256M core/scripts/drupal quick-start {{ drupal_site_name }}
  args:
    chdir: "{{ drupal_project_dir }}/web"
    creates: "{{ drupal_project_dir }}/web/sites/default/settings.php"
  when: drupal_site_name is defined

- import_tasks: db_config.yml
