- name: Ensure required packages are installed
  apt:
    name:
      - curl
      - unzip
      - php
      - php-mysql
      - php-gd
      - php-dom
      - php-xml
      - php-mbstring
      - php-curl
      - php-zip
      - apache2
    state: present
    update_cache: yes

- name: Download Drupal
  get_url:
    url: https://ftp.drupal.org/files/projects/drupal-10.2.5.tar.gz
    dest: /tmp/drupal.tar.gz

- name: Extract Drupal
  unarchive:
    src: /tmp/drupal.tar.gz
    dest: /tmp/
    remote_src: yes

- name: Remove existing web root (optional - use with caution)
  file:
    path: /var/www/html
    state: absent

- name: Copy Drupal to web root
  copy:
    src: /tmp/drupal-10.2.5/
    dest: /var/www/html/
    remote_src: yes

- name: Set permissions for Drupal directory
  file:
    path: /var/www/html
    state: directory
    recurse: yes
    owner: www-data
    group: www-data

- name: Restart Apache
  service:
    name: apache2
    state: restarted
