---

- name: Ensure Composer is installed
  stat:
    path: "{{ composer_path }}"
  register: composer_check

- name: Fail if Composer is not installed
  fail:
    msg: "Composer not found at {{ composer_path }}. Please install Composer before running this role."
  when: not composer_check.stat.exists

- name: Ensure web root directory exists
  file:
    path: "{{ web_root }}"
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: Remove existing Drupal directory (if re-provisioning)
  file:
    path: "{{ drupal_project_dir }}"
    state: absent
  when: drupal_project_dir is defined and force_reinstall | default(false)

- name: Create Drupal project directory
  file:
    path: "{{ drupal_project_dir }}"
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: Check if Drupal installation directory exists
  stat:
    path: "{{ drupal_project_dir }}/web"
  register: drupal_web_dir

- name: Set drupal_installed fact
  set_fact:
    drupal_installed: "{{ drupal_web_dir.stat.exists }}"

- name: Install Drupal using Composer
  command: >
    {{ composer_path }} create-project {{ composer_project }} {{ drupal_project_dir }}
  args:
    chdir: "{{ web_root }}"
  environment:
    COMPOSER_ALLOW_SUPERUSER: "1"
  register: drupal_composer_result
  changed_when: "'Installing drupal/core' in drupal_composer_result.stdout"
  failed_when: drupal_composer_result.rc != 0
  when: not drupal_installed

- name: Fail if Drupal installation failed
  stat:
    path: "{{ drupal_project_dir }}/web"
  register: post_install_check
  failed_when: not post_install_check.stat.exists
  when: not drupal_installed
  
- name: Install Drush globally
  import_tasks: install_drush.yml
  tags: drush

#- name: Quick start Drupal site (e.g. Umami demo)
 # shell: >
  #  php -d memory_limit=256M core/scripts/drupal quick-start {{ drupal_site_name }}
  #args:
  #  chdir: "{{ drupal_project_dir }}/web"
   # creates: "{{ drupal_project_dir }}/web/sites/default/settings.php"
  #when: drupal_site_name | length > 0 and not drupal_installed

- import_tasks: db_config.yml
  when: drupal_installed
