---
- name: Download and extract Drupal
  ansible.builtin.unarchive:
    src: "https://www.drupal.org/download-latest/tar.gz"
    dest: /var/www/
    remote_src: yes

- name: Set correct permissions on Drupal directory
  ansible.builtin.file:
    path: /var/www/drupal-*
    owner: www-data
    group: www-data
    recurse: yes
    state: directory


