apiVersion: v1
kind: Secret
metadata:
  name: {{ include "drupal.fullname" . }}-secret
  labels:
    app: {{ include "drupal.name" . }}
type: Opaque
data:
  drupal-password: {{ .Values.drupalSecrets.password | b64enc | quote }}
  db-password: {{ .Values.drupalSecrets.dbPassword | b64enc | quote }}
  db-user: {{ .Values.drupalSecrets.dbUser | b64enc | quote }}
  db-name: {{ .Values.drupalSecrets.dbName | b64enc | quote }}
