replicaCount: 3

image:
  repository: drupal
  tag: "latest"
  pullPolicy: IfNotPresent

drupalSecrets: {}  

resources:
  limits:
    cpu: "750m"
    memory: "1024Mi"
  requests:
    cpu: "300m"
    memory: "512Mi"

service:
  type: ClusterIP
  port: 80

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 10Gi
  storageClass: "gp3"

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: drupal.example.com
      paths:
        - path: /
          pathType: Prefix
  tls: [] # Add TLS secret references here if needed

nodeSelector: {}

tolerations: []

affinity: {}
